### ISSUE TITLE
trouble on 64bit system

### ISSUE THREAD

**Issue by torpak** [moriyoshi/pulsego#2]
When i compile hello.go and run it on my system (ubuntu natty 64 bit)
it crashes with the following error log:
panic: reflect.Value.UnsafeAddr of unaddressable value

runtime.panic+0xac /home/arne/go/src/pkg/runtime/proc.c:1060
    runtime.panic(0x4459a0, 0xf8400013c0)
reflect.Value·UnsafeAddr+0xd7 /home/arne/go/src/pkg/reflect/value.go:1436
    reflect.Value·UnsafeAddr(0x445318, 0xbf4ccccd, 0x0, 0xf800000000, 0x445318, ...)
pulse._PulseStream·Write+0xf7 /home/arne/pulsego/_obj/pulse.cgo1.go:-242
    pulse._PulseStream·Write(0xf8400013d0, 0x444d58, 0xf84002f000, 0xbf4ccccd00000000, 0xbf4ccccdbf4ccccd, ...)
main.myMain+0x349 /home/arne/pulsego/hello.go:41
    main.myMain(0xf84000c9b0, 0xf840000040, 0x7fc81008c100, 0x7fc81008cfb8)
----- stack segment boundary -----
runtime.goexit /home/arne/go/src/pkg/runtime/proc.c:178
    runtime.goexit()
----- goroutine created by -----
main.main+0x87 /home/arne/pulsego/hello.go:51

goroutine 1 [1]:
runtime.gosched+0x5c /home/arne/go/src/pkg/runtime/proc.c:603
    runtime.gosched()
runtime.chanrecv+0x458 /home/arne/go/src/pkg/runtime/chan.c:329
    runtime.chanrecv(0xf84000c9b0, 0x7fc81008bf88, 0x0, 0x0, 0x4026c2, ...)
runtime.chanrecv1+0x4a /home/arne/go/src/pkg/runtime/chan.c:424
    runtime.chanrecv1(0xf84000c9b0, 0xf840000040)
main.main+0x97 /home/arne/pulsego/hello.go:52
    main.main()
runtime.mainstart+0xf /home/arne/go/src/pkg/runtime/amd64/asm.s:77
    runtime.mainstart()
runtime.goexit /home/arne/go/src/pkg/runtime/proc.c:178
    runtime.goexit()
----- goroutine created by -----
_rt0_amd64+0x8e /home/arne/go/src/pkg/runtime/amd64/asm.s:64

When i compile it on my work pc (ubuntu natty 32bit) it works.

**Comment by torpak** [comment]
Project seems dead.
